### ISSUE TITLE
Jar in Maven repo does not contain native lib

### ISSUE THREAD

**Issue by svladykin** [odnoklassniki/one-nio#19]
Looks like `libonenio.so` is missing in jar deployed in Maven

**Comment by incubos** [comment]
Yes, we haven't been able to automate building the binary artifact yet, so Java implementations are used where possible. PR would be awesome!
Meanwhile, you can build `libonenio.so` for your platform manually.

**Comment by incubos** [comment]
Release 1.0.1 will appear in Maven Central soon.
@svladykin thank you!
