### ISSUE TITLE
Warning for unused classes

### ISSUE THREAD

**Issue by vlad-bondarenko** [odnoklassniki/one-nio#25]
Hi!

After running my app, output to log:
мар 31, 2018 5:35:31 PM one.nio.serial.Repository addOptionalBootstrap
WARNING: Missing optional bootstrap class: one.app.remote.reflect.MethodId
мар 31, 2018 5:35:31 PM one.nio.serial.Repository addOptionalBootstrap
WARNING: Missing optional bootstrap class: one.app.remote.comp.RemoteMethodCallRequest

I see source code and found row on one.nio.serial.Repository:
addOptionalBootstrap("one.app.remote.reflect.MethodId");
addOptionalBootstrap("one.app.remote.comp.RemoteMethodCallRequest");

This rows is garbage?

Thanks.

**Comment by apangin** [comment]
Optional classes belong to our remoting framework which is not yet open source.
I think I'll improve this part of integration so that one-nio users won't see annoying warnings.

**Comment by vlad-bondarenko** [comment]
Thanks.

**Comment by apangin** [comment]
Fixed in 992fd093bf5afc1759143133308b008f1cd55d4e
