### ISSUE TITLE
 Pool checker unhappy:  borrowObject() and returnObject() in Pool only operate the first object

### ISSUE THREAD

**Issue by little-pan** [odnoklassniki/one-nio#34]
In the one.nio.pool.Pool, the object allocation and deallocation only occurs in the head of the pool. This way or strategy leads to other objects can't be checked in a pool heartbeat checker of application:
```java
 public final T borrowObject() throws PoolException, InterruptedException {
        synchronized (this) {
            for (long timeLimit = 0; ; ) {
                // First try to get an idle object from the queue
                T object = pollFirst();
                if (object != null) {
                    return object;
                }
```
```java
    public final void returnObject(T object) {
        synchronized (this) {
            if (!closed) {
                if (waitingThreads > 0) notify();
                addFirst(object); // Using addLast() for pool checker friendly
                return;
            }
        }
        destroyObject(object);
    }
```
Suggest that Using addLast() instead of addFirst() in Pool.returnObject(), and no performance loss in LinkedList.

**Comment by apangin** [comment]
This is the intended behavior.
In the past I benchmarked both stratagies, and LIFO appears to perform slightly better while keeping the smaller number of active objects.

I could probably add an option to choose between FIFO/LIFO, but the defaults are not going to change anyway.

**Comment by apangin** [comment]
Added `Pool.fifo` and `fifo` ConnectionString option.
https://github.com/odnoklassniki/one-nio/commit/6604ab2232334bc4279180a44ed54f62f02a4321
