### ISSUE TITLE
How to implement a request filter in HttpServer

### ISSUE THREAD

**Issue by forchid** [odnoklassniki/one-nio#35]
I want to add a user login check handler in my application when using the HttpServer, but I can't find a graceful way to do this in one.nio.http package.

**Comment by apangin** [comment]
I think `HttpServer.handleRequest` is a right extension point for this.
What alternatives can you suggest if it does not suit?

**Comment by little-pan** [comment]
If overriding  httpServer.handleRequest() , the user must handle the duplicated path and virtualHost route logic. Can we add @Filter annotation as @Path in Route class? eg. @Filter("/member/*"), @Filter("*.do").

**Comment by little-pan** [comment]
@Filter really is a filter, as servlet filter, called before any matched @Path.
