### ISSUE TITLE
Missing dependency tools.jar in open JDK 11.0.x

### ISSUE THREAD

**Issue by sherman** [odnoklassniki/one-nio#39]
Hi, Andrew!

Trying to use one-nio 1.1.0 in my project, I faced with the problem: maven doesn't build the project because, since JDK9, [tools.jar were removed from the distributive](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-2C896CA8-927C-4381-A737-B1D81D964B7B).
Do you have any workaround for that?

**Comment by apangin** [comment]
JDK 11 build has been fixed.
There is no more dependency on tools.jar
