### ISSUE TITLE
undefined symbol: OPENSSL_init_ssl

### ISSUE THREAD

**Issue by asurovenko** [odnoklassniki/one-nio#45]
Hi!
I built my app with one-nio 1.2.0 and it doesn't start. In logs I can see:
`/usr/bin/java: symbol lookup error: /tmp/libonenio.97307c0a.so: undefined symbol: OPENSSL_init_ssl`
Both servers: where I built and where I tryed to start, have openssl version **1.0.2k-fips**
What I should do?

**Comment by avrecko** [comment]
I had similar issue. I just compiled/built one-nio on my fedora box and
deployed to internal maven repository. It works fine. Very happy with it.

**Comment by apangin** [comment]
Apparently, the maven artifact was built with OpenSSL 1.1.x and hence does not work on systems with OpenSSL 1.0.2.

The workaround is to use [one-nio-1.2.0.jar](https://github.com/odnoklassniki/one-nio/releases/download/1.2.0/one-nio-1.2.0.jar) from the [releases](https://github.com/odnoklassniki/one-nio/releases/tag/1.2.0) page (it should work everywhere) or to build the .jar yourself.

@incubos can you please re-publish the artifact built against OpenSSL 1.0.2?

**Comment by incubos** [comment]
AFAIK, it is impossible to rewrite an artifact released to Maven Central, so we will have to release a new version. I will reach my laptop next week and will do it.

Best regards,
    Vadim Tsesko

**Comment by asurovenko** [comment]
**incubos**, it is still actual? I'm waiting :)

**Comment by incubos** [comment]
Unfortunately, I am not able to build a backwards compatible version of `libonenio.so` easily.
@apangin released 1.2.1 to Maven Central using the dedicated build environment. The artifact should become accessible within a day.
