### ISSUE TITLE
Ignore Content-Length when using chunked transfer encoding

### ISSUE THREAD

**Issue by incubos** [odnoklassniki/one-nio#49]
See [HTTP/1.1](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html):

> Messages MUST NOT include both a Content-Length header field and a non-identity transfer-coding. If the message does include a non- identity transfer-coding, the Content-Length MUST be ignored.

**Comment by apangin** [comment]
Thank you for the fix
