### ISSUE TITLE
Central repositories

### ISSUE THREAD

**Issue by Rexhaif** [odnoklassniki/one-nio#5]
Hi!
What about to add this package to Maven Central and/or to JCenter?

**Comment by apangin** [comment]
Yes, it's definitely worth doing.

**Comment by incubos** [comment]
I will try to do it.

**Comment by incubos** [comment]
Released `1.0-SNAPSHOT`: https://oss.sonatype.org/content/groups/public/ru/odnoklassniki/one-nio/1.0-SNAPSHOT/

**Comment by incubos** [comment]
Released `ru.odnoklassniki:one-nio:1.0.0`. It is going to be available in Maven Central soon.
The native library still has to be built manually.
