### ISSUE TITLE
HttpClient extra whitespace break Transfer-Encoding chunked header

### ISSUE THREAD

**Issue by avrecko** [odnoklassniki/one-nio#57]
As in the title. We noticed that if the server returns some extra whitespace for transfer-encoding header this condition isn't met.

```
  if (method != Request.METHOD_HEAD && mayHaveBody(response.getStatus())) {
                if ("chunked".equalsIgnoreCase(response.getHeader("Transfer-Encoding: "))) {
                    response.setBody(readChunkedBody());
                } else { 
```

**Comment by apangin** [comment]
Can you give an example of such header?
I suppose, it'll be enough to just trim the value of the header before comparing, right?

**Comment by avrecko** [comment]
For header, if there is an extra whitespace after ':'. Such as `Transfer-Encoding:<space><space>chunked` Some 3rd party servers aren't nice and add some extra whitespace.

Yes, trim please. Afaik, by http spec values should be trimmed. But I appreciate the extra level of control one-nio offers.

Maybe add `getHeader(String,Boolean[trim])` method?

**Comment by apangin** [comment]
I think it's OK to left-trim headers by default, both in `Request` and `Response`.
Will fix it in the next release.

**Comment by avrecko** [comment]
How about both? https://tools.ietf.org/html/rfc7230#section-3.2.4

```
   A field value might be preceded and/or followed by optional
   whitespace (OWS); a single SP preceding the field-value is preferred
   for consistent readability by humans.  The field value does not
   include any leading or trailing whitespace: OWS occurring before the
   first non-whitespace octet of the field value or after the last
   non-whitespace octet of the field value ought to be excluded by
   parsers when extracting the field value from a header field.
```

**Comment by apangin** [comment]
Alright. Though I doubt there are actual implementations sending _trailing_ spaces, there's no problem in checking this either.

**Comment by avrecko** [comment]
Great. Right trim is a good idea as well. Example: https://github.com/envoyproxy/envoy/security/advisories/GHSA-356m-vhw2-wcm4

**Comment by apangin** [comment]
I've just synced one-nio with our internal repo. That included HttpClient fix.
