### ISSUE TITLE
Moving of mem package to separate repository

### ISSUE THREAD

**Issue by vvsh** [odnoklassniki/one-nio#6]
Hi Andrey,

What do you think about moving of OffheapMap, SharedMemoryMap and etc. mem.* to separate repository to use them without one-nio?

Thanks.

**Comment by apangin** [comment]
Hi. What's the purpose of doing so? SharedMemoryMap depends on many other parts of one-nio: util, lock, serialization, bytecode generation etc.

**Comment by vvsh** [comment]
Yes, I agree with you, but I would be great to use only this classes without copy-paste or dependency on whole one-nio.

**Comment by apangin** [comment]
one-nio is a small library, and SharedMemoryMap depends on a half of it.
It does not seem necessary to split this into parts.

**Comment by vvsh** [comment]
Ok, I see.
