### ISSUE TITLE
Java 17 is supported

### ISSUE THREAD

**Issue by vlad-bondarenko** [odnoklassniki/one-nio#61]
Hi!

Java 17 is supported?
How run to java 17?

**Comment by apangin** [comment]
Yes, I recently committed JDK 17 related fixes.
The latest code from `master` should work with JDK 17 out of the box.
It hasn't been published in Maven Central though. Will do it soon.

**Comment by vlad-bondarenko** [comment]
Thanks.

**Comment by apangin** [comment]
one-nio 1.5.0 has been published.
