### ISSUE TITLE
one-nio version >=1.6.1 doesn't work with glibc 2.31

### ISSUE THREAD

**Issue by Blooof** [odnoklassniki/one-nio#76]
I have stock Debian 11 with kernel 5.10.162, compiled with glibc 2.31.
All versions of one-nio prior to 1.6.1 worked on my setup. 
But since 1.6.1 it requires at least glibc 2.34 (ldd libonenio.so says "version `GLIBC_2.34' not found").
Please consider rebuild project with old version of glibc.

**Comment by incubos** [comment]
Released `1.7.1` with GLIBC 2.2.5.
