### ISSUE TITLE
Is there any way to handle HTTPS in HttpClient?

### ISSUE THREAD

**Issue by asurovenko-zeta** [odnoklassniki/one-nio#83]
Hello!

As I understand there's no support for HTTPS in current implementation of HttpClient
Maybe there's any way to handle it?

Thanks!

**Comment by asurovenko-zeta** [comment]
Because I always receive the following when sending through https
```
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
</body>
</html>
```

**Comment by apangin** [comment]
[There is](https://github.com/odnoklassniki/one-nio/blob/master/src/one/nio/http/HttpClient.java#L56-L59) https support on Linux.
